### ISSUE TITLE
How to integrate this as watcher in broccoli?

### ISSUE THREAD

**Issue by harianus** [krisselden/broccoli-sane-watcher#30]
I can't find any docs on *broccoli-sane-watcher*, is it meant to integrate it in the `Brocfile.js` or the `cli`?

We have *broccoli* running with some people on one dev-server, and it consumes almost all the CPU.

**Comment by stefanpenner** [comment]
> We have broccoli running with some people on one dev-server, and it consumes almost all the CPU.

I don't believe the broccoli-cli is pluggable. If you want this quickly (without any extra effort) feel free to use `ember-cli` although it is named ember, it can build any Brocfile and comes with the watcher out of the box.

**Comment by harianus** [comment]
> If you want this quickly (without any extra effort) feel free to use `ember-cli`

Wow, that works like a charm. The CPU usage in idle mode dropped from ~55% to 0%. Now I need to convince the rest of the team to change the api to a full REST so I can use EmberJS again ;-)

Thanks @stefanpenner!

**Comment by stefanpenner** [comment]
> change the api to a full REST so I can use EmberJS again ;-)

ember works with any API ;)
